### ISSUE TITLE
JPG stickers not uploading

### ISSUE THREAD

**Issue by panthshadowclaw** [NewFuture/custom-stickers-teams-extension#35]
Hello, trying to upload the following jpeg picture as a sticker, which is not working
![angry](https://user-images.githubusercontent.com/49696586/116255605-663dbe00-a740-11eb-8e93-7187eef4f04f.jpg)
Unsure what other info I could give to assist.

**Comment by panthshadowclaw** [comment]
Not limited to this single image.  Multiple jpeg files do not seem to be uploading correctly.

**Comment by NewFuture** [comment]
Sorry for that.
In fact, this image is a WEBP image instead of a JPEG.
![image](https://user-images.githubusercontent.com/6290356/116380844-ee0df000-a846-11eb-9c01-85af114fa11f.png)

Teams will transfer all images in the cards on content servers now.
But it does NOT support WEBP images.
so all WEBP images are broken now.

Related 
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/41772103-support-the-webp-format-for-things-link-announcem
